# Tarea Semana 2: FUNDAMENTOS DE PYTHON
## Nombre: Gerardo Figueroa Golarte

#### Ejercicio 1
 Las matemáticas financieras, resumidas en una frase, las podríamos definir como la rama de las matemáticas que estudia los flujos de dinero a través del tiempo. Básicamente se presupone que el dinero tiene menos valor en el futuro que en el presente, ya sea por un tema inflacionario o por la preferencia natural de las personas a priorizar el consumo presente.

 El valor futuro es el valor alcanzado por un determinado capital al final del período determinado (para el ejemplo usaremos la fórmula del interés compuesto). Para calcularlo se utiliza la siguiente fórmula

VF=VA* ( 1+i )n

 El valor presente de una inversión es cuando calculamos el valor actual que tendrá una determinada cantidad que recibiremos o pagaremos en un futuro. Para calcularlo se utiliza la siguiente fórmula

VA=VF( 1+i )n 

 Donde 
 - VF es el valor futuro, 
 - VA es el valor actual o inicial de la inversión, 
 - i es el tipo de interés y 
 - n es número de años de la inversión.

A. Crear una función que reciba como entrada un capital, un tipo de interés y un número de años, y muestre por pantalla el valor futuro de la inversión cada año del periodo indicado.

B. Crear una función que reciba como entrada un capital, un tipo de interés y un número de años, y muestre por pantalla el valor actual del capital cada año del periodo indicado.

In [6]:
def valorfuturo(capital, interes, años):
    vf = capital * ((1 + interes)**años)
    return vf

def valoractual(capital, interes, años):
    va = capital / ((1 + interes)**años)
    return va

valorfuturo(1000, 10, 1)
valoractual(11000, 10, 1)

1000.0

#### Explicación:
Solamente introducí la fórmula que venía en el ejercicio en una función. Por practicidad, asigné la formula a una variable y la función regresa la variable.

## Ejercicio 2
El archivo cotización.csv (archivo adjunto ) contiene las cotizaciones de empresas con las siguientes columnas: 
 - Nombre (nombre de la empresa), 
 - Final (precio de la acción al cierre de bolsa), 
 - Máximo (precio máximo de la acción durante la jornada), 
 - Mínimo (precio mínimo de la acción durante la jornada), 
 - Volumen (Volumen al cierre de bolsa), 
 - Efectivo (capitalización al cierre en miles de euros).

A. Construir una función reciba el fichero de cotizaciones y devuelva un diccionario con los datos del fichero por columnas.

B. Construir una función que reciba el diccionario devuelto por la función anterior y cree un fichero en formato csv con el mínimo, el máximo y la media de cada columna.

In [26]:
import pandas as pd

data=pd.read_csv(folder+filename, sep=";")
data

          Nombre   Final  Máximo  Mínimo     Volumen   Efectivo
0        ACCIONA   95,95   96,75    94,4      84.962    8166,11
1       ACERINOX    8668    8672    8468      885.99    7633,81
2            ACS   37,28   37,66   37,22     655.982   24517,29
3           AENA   167,1   167,5   166,1     133.738   22336,10
4        AMADEUS   69,96   70,64   69,56     640.476   44795,47
5    ARCELORMIT.   14152   14318   14,08     702.841    9989,65
6    BA.SABADELL  1,0165    1033  1,0165  12.358.512   12637,65
7   BA.SANTANDER    4,02  4,0675    4,01  36.129.692  145765,44
8         BANKIA    2249    2262    2224   3.024.454    6803,54
9      BANKINTER    6,56    6604    6522   1.375.976    9030,20
10          BBVA    5024    5,05    4969  26.447.612  132560,15
11     CAIXABANK    2763    2806    2762  13.031.097   36239,22
12       CELLNEX   30,17    30,7   30,17     857.237   25965,29
13  CIE AUTOMOT.   23,44   23,74    23,4      99.506    2343,09
14        ENAGAS    25,6   25,66   25,07      842.54   21524,77
15          ENCE    3882    3974    3846   2.099.698    8219,83
16        ENDESA   22,95   23,03   22,62   1.236.799   28233,46
17     FERROVIAL   21,61   21,72   21,38   2.065.931   44656,05
18  GRIFOLS CL.A    23,3    23,6   23,27     719.503   16787,55
19           IAG     5,3    5,46    5292   2.155.081   11561,95
20     IBERDROLA    8,45    8,45    8262  15.637.958  131426,05
21       INDITEX   24,93   25,19   24,87   2.600.144   65012,92
22       INDRA A    9,56    9685    9535      392.06    3755,57
23  INM.COLONIAL    9915    9915    9745     671.753    6640,38
24        MAPFRE    2654    2654    2,62   3.045.972    8063,13
25      MEDIASET    6446    6592    6446   2.647.557   17277,04
26  MELIA HOTELS    8,14    8,19    8,02      480.21    3914,93
27        MERLIN   12,08   12,08   11,83     777.543    9357,77
28       NATURGY    26,7   26,77   26,53   2.100.737   55986,54
29        R.E.C.   19705   19875   19675   1.246.171   24585,33
30        REPSOL   14515   14605   14,46   5.046.648   73333,78
31  SIEMENS GAME   14,33   14,39   14155   1.054.847   15084,56
32  TEC.REUNIDAS      23    23,2   22,78       122.1    2807,19
33    TELEFONICA    7204    7256    7185   9.913.249   71564,99
34      VISCOFAN   48,46   49,12   48,46       67.71    3295,43

In [23]:
import pandas as pd
import locale

locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
folder = 'C:\\Users\\gefig\\OneDrive\\Desktop\\Aleita\\Python Projects\\'
filename = "cotizacion.csv"

def csvtodict(filename,key):
    df = pd.read_csv(folder+filename, sep=";")
    d = df.to_dict(orient='list')
    return d[key]

listafinalstr = csvtodict(filename,'Final')
listamaximostr = csvtodict(filename,'Máximo')
listaminimostr = csvtodict(filename,'Mínimo')
listavolumenstr = csvtodict(filename,'Volumen')
listaefectivostr = csvtodict(filename,'Efectivo')

listafinal = []
for s in listafinalstr:
    s = s.replace(",",".")
    s=float(s)
    listafinal.append(s)
    
listamaximo = []
for s in listamaximostr:
    s = s.replace(",",".")
    s=float(s)
    listamaximo.append(s)
    
listaminimo = []
for s in listaminimostr:
    s = s.replace(",",".")
    s=float(s)
    listaminimo.append(s)
    
listaefectivo = []
for s in listaefectivostr:
    s = s.replace(",",".")
    s=float(s)
    listaefectivo.append(s)

listavolumen = []
for s in listavolumenstr:
    if s.count('.') == 2:
        s = s.replace('.', '', 1)
    s = s.replace(',', '.')
    s = float(s)
    listavolumen.append(s)
    
maxfin = max(listafinal)
minfin = min(listafinal)
avgfin = sum(listafinal)/len(listafinal)

maxmax = max(listamaximo)
minmax = min(listamaximo)
avgmax = sum(listamaximo)/len(listamaximo)

maxmin = max(listaminimo)
minmin = min(listaminimo)
avgmin = sum(listaminimo)/len(listaminimo)

maxvol = max(listavolumen)
minvol = min(listavolumen)
avgvol = sum(listavolumen)/len(listavolumen)

maxef = max(listaefectivo)
minef = min(listaefectivo)
avgef= sum(listaefectivo)/len(listaefectivo)

cotstats = {'Final': [maxfin, minfin, avgfin], 'Máximo': [maxmax, minmax, avgmax], 'Mínimo': [maxmin, minmin, avgmin], 'Volumen' : [maxvol, minvol, avgvol], 'Efectivo': [maxef, minef, avgef]}

df = pd.DataFrame(cotstats)

filename = 'Cotiztats.csv'

df.to_csv(filename, index=False)

#### Explicación: 
Se me dificultó al principio cambiar las listas de strings a integers por las comas. Me enredé tratando de convertir los elemnots a float mientras cambiaba el formato también.
Pero ya en formato de list en floats, opté por utilizar las funciones directas de max(), min() y para promedio utilice sum()/len()
Se me ha dificultado hacerlo en una función. Creo que podría utilizar un loop que pasara por los keys e hiciera todo lo que hice uno a uno con las listas y al mismo tiempo creara variables para insertar en un nuevo diccionario. Todo esto es nuevo para mí por lo que me ha dejado exhausto mentalmente. Planeo pasar por los demás ejercicios y después volver a este a mejorar el código.

#### Ejercicio 3
Escribir un programa para gestionar un listado telefónico con los nombres y los teléfonos de los clientes de una empresa. 
    
    A. El programa debe crear el archivo TXT con la lista si no existe
    B. El programa debe  tener una función para consultar el teléfono de un cliente e imprimirlo en pantalla.
    C. El programa debe  tener una función para  añadir el teléfono de un nuevo cliente al archivo TXT.
    D. El programa debe tener una función que permita visualizar todo el listado telefónico
    E. El programa debe tener una función que guarde esta lista en un archivo CSV.

In [32]:
clientnphone = {'Giorgio Armani': 66234567, 'Snoop Dogg': 66420420}
filename = 'Clientnphone.txt'

with open(filename, 'w') as file:
    for key, value in clientnphone.items():
        file.write(f"{key}: {value}\n")
        
#find number from txt.
def getphone(clientname):
    key_to_retrieve = clientname
    with open(filename, 'r') as file:
        for line in file:
            key, value = line.strip().split(": ")
            if key == key_to_retrieve:
                 print(f"The value for key '{key_to_retrieve}' is: {value}")
getphone('Giorgio Armani')

def addphonenewclient(name, phone):
    with open(filename,'a') as file:
        file.write(f"{name}: {phone}\n")
addphonenewclient('Julius Caesar', 66213243)

def readwhlist(filename):
    with open(filename,'r') as file:
        return file.read()
     
readwhlist(filename)

input_filename = 'Clientnphone.txt'
output_filename = 'Clientnphone.csv'

def tocsv(input_filename):
    df = pd.read_csv(input_filename, delimiter="\t")
    df.to_csv(output_filename, index=False)
    print(f"File '{input_filename}' has been converted to '{output_filename}' successfully!")
    
tocsv(input_filename)

#### Explicación: 
Se me dificultó bastante. Para mí los diccionarios y el manejo de archivos todavía es muy nuevo. Escribí lo que yo pude solo de código y luego investigaba como hacerlo. Me faltaban una o dos lineas de código o solo tocaba formatear correctamente las funciones u operaciones. Me ha servido mucho para comprender cómo se manejan los archivos y la variedad de formas y utilidades que pueden tomar los diccionarios. También aprendí de pandas y los dataframes.

#### Ejercicio 4
El archivo calificaciones.csv (archivo adjunto ) contiene las calificaciones de un curso. Durante el curso se realizaron dos exámenes parciales de teoría y un examen de prácticas. Escribir un programa que contenga las siguientes funciones:

    A. Una función que reciba el archivo de calificaciones y devuelva una lista de diccionarios, donde cada diccionario contiene la información de los exámenes y la asistencia de un alumno. La lista tiene que estar ordenada por apellidos.
    B. Una función que reciba una lista de diccionarios como la que devuelve la función anterior y añada a cada diccionario una nueva llave con la nota final del curso.  Teniendo en cuenta los siguientes criterios de evaluación 
         - Practicas 10 %
         - Practica Final 30% 
         - Promedio de Parciales 1 y 2  20%
         - Promedio de Exámenes 1 y 2 40%
    C. Una función que reciba una lista de diccionarios como la que devuelve la función anterior y devuelva dos listas, una con los alumnos aprobados y otra con los alumnos suspensos. Para aprobar el curso
         - La asistencia tiene que ser mayor o igual que el 75%
         - La nota final debe ser mayor o igual a 8.0

In [3]:
import pandas as pd
folder = 'C:\\Users\\gefig\\OneDrive\\Desktop\\Aleita\\Python Projects\\'
filename3 = "calificaciones.csv"

def scoresdictfunc(filename):
    df = pd.read_csv(folder+filename)
    column1_data = df['Asistencia'].tolist()
    column2_data = df['Examen1'].tolist()
    column3_data = df['Examen2'].tolist()
    column4_data = df['Apellidos'].tolist()
    column5_data = df['Practica Final'].tolist()
    column6_data = df['Parcial1'].tolist()
    column7_data = df['Parcial2'].tolist()
    column8_data = df['Practicas'].tolist()
    list_of_dicts = [{ 'Apellidos': nombre, 'Asistencia': asistencia, 'Examen1': examen1, 'Examen2':examen2, 'Practica Final': practicafinal, 'Parcial1' : parcialuno, 'Parcial2' : parcialdos, 'Practicas' : practicas} for nombre, asistencia, examen1, examen2, practicafinal, parcialuno, parcialdos, practicas in zip(column4_data ,column1_data, column2_data, column3_data, column5_data, column6_data, column7_data, column8_data)]
    sorted_list_of_dicts = sorted(list_of_dicts, key=lambda x: x['Apellidos'])
    return sorted_list_of_dicts
scoresdictfunc(filename3)

[{'Apellidos': 'Anido Bonet',
  'Asistencia': '90%',
  'Examen1': 0,
  'Examen2': 5.0,
  'Practica Final': 0.0,
  'Parcial1': 5.5,
  'Parcial2': 2.75,
  'Practicas': 0.0},
 {'Apellidos': 'Bueno Cerdeira',
  'Asistencia': '95%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 9.5,
  'Parcial2': 9.0,
  'Practicas': 6.25},
 {'Apellidos': 'Casariego García',
  'Asistencia': '98%',
  'Examen1': 6,
  'Examen2': 0.0,
  'Practica Final': 5.0,
  'Parcial1': 4.25,
  'Parcial2': 5.75,
  'Practicas': 4.0},
 {'Apellidos': 'Curbelo Sánchez',
  'Asistencia': '75%',
  'Examen1': 5,
  'Examen2': 0.0,
  'Practica Final': 6.5,
  'Parcial1': 6.75,
  'Parcial2': 4.25,
  'Practicas': 0.0},
 {'Apellidos': 'Díaz Souto',
  'Asistencia': '82%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 7.0,
  'Parcial2': 6.5,
  'Practicas': 9.0},
 {'Apellidos': 'García Perez',
  'Asistencia': '85%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 10.0,
  'Parcial2': 8.0,
  'Practicas': 7.5},
 {'Apellidos': 'Lorenzo García',
  'Asistencia': '100%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 9.75,
  'Parcial2': 8.25,
  'Practicas': 7.5},
 {'Apellidos': 'Martínez Lucas',
  'Asistencia': '86%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 7.0,
  'Parcial2': 4.0,
  'Practicas': 6.25},
 {'Apellidos': 'Mora Peñaloza',
  'Asistencia': '70%',
  'Examen1': 0,
  'Examen2': 4.0,
  'Practica Final': 0.0,
  'Parcial1': 5.25,
  'Parcial2': 2.0,
  'Practicas': 6.5},
 {'Apellidos': 'Moreno Angulo',
  'Asistencia': '88%',
  'Examen1': 4,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 9.0,
  'Parcial2': 6.75,
  'Practicas': 5.25},
 {'Apellidos': 'Morillo Escudero',
  'Asistencia': '100%',
  'Examen1': 3,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 9.5,
  'Parcial2': 10.0,
  'Practicas': 8.75},
 {'Apellidos': 'Muñoz Gómez',
  'Asistencia': '94%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 7.75,
  'Parcial2': 6.5,
  'Practicas': 4.0},
 {'Apellidos': 'Ramirez de la Puente',
  'Asistencia': '75%',
  'Examen1': 1,
  'Examen2': 2.75,
  'Practica Final': 3.25,
  'Parcial1': 0.0,
  'Parcial2': 1.0,
  'Practicas': 2.25},
 {'Apellidos': 'Riego Pizarro',
  'Asistencia': '75%',
  'Examen1': 5,
  'Examen2': 3.75,
  'Practica Final': 0.0,
  'Parcial1': 4.0,
  'Parcial2': 2.5,
  'Practicas': 0.0},
 {'Apellidos': 'Rodríguez de Blas',
  'Asistencia': '80%',
  'Examen1': 0,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 8.25,
  'Parcial2': 5.25,
  'Practicas': 6.5},
 {'Apellidos': 'Sánchez Jordán',
  'Asistencia': '92%',
  'Examen1': 7,
  'Examen2': 0.0,
  'Practica Final': 0.0,
  'Parcial1': 8.75,
  'Parcial2': 9.0,
  'Practicas': 6.5}]

In [18]:
scores_list = scoresdictfunc(filename3)

def addavgtodict(listofdict):
    for scores in listofdict:
        examen1 = 0
        examen2 = 0
        parcial1 = 0
        parcial2 = 0
        practicas = 0
        practicafinal = 0
        totalsum = 0
        for subkey, subvalue in scores.items():
            if subkey == 'Examen1':
                examen1 = subvalue
            elif subkey == 'Examen2':
                examen2 = subvalue
            elif subkey == 'Parcial1':
                parcial1 = subvalue
            elif subkey == 'Parcial2':
                parcial2 = subvalue
            elif subkey == 'Practicas':
                practicas = subvalue
            elif subkey == 'Practica Final':
                practicafinal = subvalue
        totalsum = (((examen1+examen2)/2)*.4) + (((parcial1+parcial2)/2)*.2) + (practicas*.1) + (practicafinal*.3)
        scores['Promedio'] = totalsum
    return listofdict

for scores in newdict:
    print(scores['Promedio'])

1.8250000000000002
2.475
4.1
4.05
2.25
2.55
2.55
1.725
2.1750000000000003
2.9
3.4250000000000003
1.8250000000000002
2.05
2.4
2.0
3.825

In [15]:
def whopassed(scoresdic):
    passed = []
    flunked = []
    for scores in scoresdic:
        for key, value in scores.items():
            perstr = scores['Asistencia']
            asist = int(perstr.strip("%"))
            finsco = scores['Promedio']
            if asist > 74 and finsco > 7.9:
                passed.append(scores['Apellidos'])
            else:
                flunked.append(scores['Apellidos'])
    return passed, flunked

passed_list, flunked_list = whopassed(scores_list)

print("Passed:")
print(passed_list)
print("Flunked:")
print(flunked_list)

#### Explicación:
En la primera función comprendí como se podían extraer los datos de la tabla en listas para luego organizar en una lista de diccionarios utilizando los keys de los atributos. Me sirvió mucho para empezar a comprender las listas de diccionarios. Tenía una vaga idea de cómo hacerlo, me apoyé mucho en funciones específicas en foros.

En la segunda función se cimentó mi comprensión sobre la lista de diccionarios. Me estaba fallando por que no sabía que el primer loop era en formato de lista y yo estaba intentando hacer ambos loops como diccionario. No sabía si iba a funcionar, pensé que tal vez necesitaría crear una variable específica a cada key de cada diccionario de la lista. Logré extraer los valores de los keys de cada diccionario para darles el valor en el promedio y agregar a cada diccionario de la lista. Por dejarlo fuera del loop interior solo se había creado en el primer diccionario. 

La tercera función fue la más sencilla. Al ya saber loopear la lista de diccionarios solo formateé el string de "Asistencia", obtuve el de "Promedio" y les aplique sus respectivas condiciones dentro del loop para que se aplicara a todos los diccionarios. Una vez filtrados se agregaba a una de dos listas previamente creadas para   identificar alumnos aprobados y reprobados.